export enum LighthouseErrorMessage {
  GATEWAY_INVALID_URL = "GATEWAY_INVALID_URL",
  VALIDATION_BAD_BODY = "VALIDATION_BAD_BODY",
  VALIDATION_BAD_PARAMS = "VALIDATION_BAD_PARAMS",
  VALIDATION_BAD_QUERY = "VALIDATION_BAD_QUERY",
  CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND",
  TAG_NOT_FOUND = "TAG_NOT_FOUND",
  GROUP_STILL_HAS_CONTACTS = "GROUP_STILL_HAS_CONTACTS",
  GROUP_HAS_NO_MEMBERS = "GROUP_HAS_NO_MEMBERS",
  TAG_STILL_HAS_CONTACTS = "TAG_STILL_HAS_CONTACTS",
  DUPLICATE_TAG_NAME = "DUPLICATE_TAG_NAME",
}
